#!/usr/bin/env pwsh
# Generates a dev .env with cryptographically random secrets.
# Refuses to overwrite an existing .env unless -Force is passed.
# Usage: ./scripts/init-env.ps1 [-Force]
# ASCII-only by design (PS 5.1 / Windows-1252 source encoding pitfall).

[CmdletBinding()]
param(
    [switch]$Force
)

$ErrorActionPreference = 'Stop'
Set-Location (Split-Path -Parent $PSScriptRoot)

$envPath = '.env'
if ((Test-Path $envPath) -and -not $Force) {
    Write-Error '.env already exists. Use -Force to overwrite (current secrets will be lost).'
    exit 1
}

function New-RandomBase64 {
    param([int]$Bytes = 32)
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return [Convert]::ToBase64String($buf)
}

function New-RandomHex {
    param([int]$Bytes = 16)
    $buf = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($buf)
    return ([BitConverter]::ToString($buf) -replace '-', '').ToLower()
}

Write-Host 'Generating secrets...' -ForegroundColor Cyan
$pepper        = New-RandomBase64 32
$encryptionKey = New-RandomBase64 32
$mariaPassword = New-RandomHex 16
$mariaRootPw   = New-RandomHex 16

$content = @"
# Generated by scripts/init-env.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm')
# DO NOT COMMIT. Back up pepper + encryption-key + JWT keys off-machine.

# === Server ===
PORT=3000
NODE_ENV=development

# === MariaDB (used by docker-compose to init the db container) ===
MARIADB_ROOT_PASSWORD=$mariaRootPw
MARIADB_DATABASE=acervatim
MARIADB_USER=acervatim
MARIADB_PASSWORD=$mariaPassword

# === Database URL ===
# Outside compose (e.g. prisma:studio on Windows host): host=localhost.
# Inside compose, app uses host=db (override in docker-compose.yml).
DATABASE_URL="mysql://acervatim:$mariaPassword@localhost:3306/acervatim"

# === Crypto secrets (CRITICAL: back up off-machine) ===
# Losing the pepper = users unrecoverable.
SUB_HASH_PEPPER="$pepper"
ENCRYPTION_KEY="$encryptionKey"

# === JWT RS256 ===
# Generate after the first './scripts/dev.ps1 up':
#   ./scripts/dev.ps1 exec sh -c "openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out /tmp/jwt.pem && openssl rsa -in /tmp/jwt.pem -pubout -out /tmp/jwt.pub.pem && cat /tmp/jwt.pem /tmp/jwt.pub.pem"
# Then convert newlines to \n and paste below (wrapped in quotes).
JWT_PRIVATE_KEY=""
JWT_PUBLIC_KEY=""

# === Google OAuth Android client ID (fill once Google Cloud project is created) ===
GOOGLE_CLIENT_ID=""

# === Discogs OAuth 1.0a (from discogs.com/settings/developers) ===
DISCOGS_CONSUMER_KEY=""
DISCOGS_CONSUMER_SECRET=""
"@

# UTF-8 without BOM via .NET (Set-Content -Encoding UTF8 writes BOM on PS 5.1).
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Resolve-Path -Path $PWD).Path + '\' + $envPath, $content, $utf8NoBom)

Write-Host '.env created.' -ForegroundColor Green
Write-Host ''
Write-Host 'Generated MariaDB passwords:' -ForegroundColor Yellow
Write-Host "  root         : $mariaRootPw"
Write-Host "  acervatim    : $mariaPassword"
Write-Host ''
Write-Host 'Back up off-machine (password manager):' -ForegroundColor Yellow
Write-Host '  - SUB_HASH_PEPPER'
Write-Host '  - ENCRYPTION_KEY'
Write-Host ''
Write-Host 'To generate JWT keys (RS256, after first docker compose up):' -ForegroundColor Yellow
Write-Host '  ./scripts/dev.ps1 exec sh -c "openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out /tmp/jwt.pem && openssl rsa -in /tmp/jwt.pem -pubout -out /tmp/jwt.pub.pem && cat /tmp/jwt.pem /tmp/jwt.pub.pem"'
Write-Host '  Then escape newlines as \n and paste into JWT_PRIVATE_KEY / JWT_PUBLIC_KEY.'
